### products index
GET http://localhost:3000/products.json

### products show

GET http://localhost:3000/products/2.json

### products create

POST http://localhost:3000/products.json
Content-type: application/json

{
  "name": "name",
  "price": 1,
  "image_url": "image",
  "description": "description"
}

### products update

PATCH http://localhost:3000/products/19.json
Content-type: application/json

{
  "name": "name x2",
  "price": 3,
  "image_url": "url x2",
  "description": "description x2"
}

### products destroy

DELETE http://localhost:3000/products/17.json